### ISSUE TITLE
Establish a working model of flow distribution throughout the system

### ISSUE THREAD

**Issue by BenGassaway** [AguaClara/Trickling-Filter#10]
1.) Through observational experiments, visually characterize the flow tendencies as the water disperses through the packing material; hydraulic fingering
2.) Quantify the surface area utilization rates of a variety of packing material 
       - Hypothesis: a vast majority of the rocks remain dry as the flow is driven preferentially throughout the 
       same veins
       - The efficiency has a high potential for improvement and minimized space requirements
3.) Identify performance differences between certain packing geometries

**Comment by jillianwhiting** [comment]
Research Area of Influence in trickling filters

**Comment by jillianwhiting** [comment]
Use heat maps for analyzing data: https://plot.ly/python/heatmaps/

**Comment by zacchen15** [comment]
I found a book on aerobic biofilm reactors.  I don't know is this will help but the previous volume on anaerobic reactors has definitely helped our team.

https://www.iwapublishing.com/sites/default/files/ebooks/9781780402123.pdf

**Comment by jillianwhiting** [comment]
Analyzed data is in heat maps file in repo, rocks had more dispersed flow than marbles and wet rocks was even more dispersed than dry rocks.
