### ISSUE TITLE
RA and Matt Reid Meeting Notes

### ISSUE THREAD

**Issue by jillianwhiting** [AguaClara/Trickling-Filter#13]

**Comment by rosiekrasnoff** [comment]
3/6/18 RA meeting with Zoe:
We debriefed on the tour of the Cayuga Heights wastewater treatment plant we had last Thursday and discussed several of the issues we observed on the tour. We also briefly talked about our meeting with Prof Reid and what resources we will be focusing in on as our research continues. We updated Zoe on our plans for a bench top model we hope to start constructing soon, and she made a couple of suggestions about our design.

Our plans moving forward are to prioritize working on our report for the rest of the week, then shift our focus to the bench top model next week.

**Comment by BenGassaway** [comment]
3/6/18 Meeting with Professor Reid:

Questions to address:
A. Using Cayuga Heights Trickling Filter as a Case Study
      1. Determine if the effluent stream of the Cayuga Heights WWTF is oxygenated
      2. How quickly is the system (trickling filter) becoming anaerobic? Rather, at what depth do 
      anaerobic conditions become and issue?
      3. Use DO probe on trickling filter effluent

B. Research Focus Shift
      1. Rely more heavily on the research of textbooks: a.) Wastewater Engineering Treatment and Reuse 
      b.) Bioprocesses Textbook [Official title will be added]
      2. Identify nitrification, denitrification, and other nutrient loadings external to research in Trickling 
      Filters

C. Bench Top Tracer Test
      1. Test for short-circuiting in the system
           a. Measure breakthrough time of the dye through the filter media
       2. A very sharp curve indicates advection 
       3. A smoother s-shape will indicate a great deal of dispersion and nonuniform residence times 
       throughout the media
