### ISSUE TITLE
Research Report 2

### ISSUE THREAD

**Issue by jillianwhiting** [AguaClara/Trickling-Filter#17]

**Comment by jillianwhiting** [comment]
07617a12-5cf7-4bf9-88ee-752d00d24c8c

**Comment by jillianwhiting** [comment]
@nataliemottl As a point of clarification, for our reports are we writing to an audience of a person in the wastewater industry or a general person? (i.e. a wastewater industry person would know general information about trickling filters whereas a general person we should describe everything)

**Comment by jillianwhiting** [comment]
We think the level of audience for this report should be someone who has taken a basics wastewater class like 3510 (because that is what people who are joining the team should have). Therefore we will not explain what a trickling filter is but will go into depth about parameters of the filter we will be changing.

**Comment by jillianwhiting** [comment]
162588e4-2d4b-438a-ab69-fe449d5b123d

**Comment by BenGassaway** [comment]
IT'S...... PORTAL TIME atom://teletype/portal/38774604-3501-44a3-894a-58c7755a5173

**Comment by rosiekrasnoff** [comment]
portal time: atom://teletype/portal/f6b61ce9-5cca-40ea-a258-718148330c4c
