### ISSUE TITLE
String (theory) Prototype flow tests

### ISSUE THREAD

**Issue by jillianwhiting** [AguaClara/Trickling-Filter#18]

**Comment by jillianwhiting** [comment]
Tests to be conducted
1. Varying flow rate
2. Varying string spacing
3. Varying anchoring points

**Comment by jillianwhiting** [comment]
Comments from preliminary test to make sure water flowed down the strings:

- preference for wet strings, dry strings stay dry because water down not flow down them
- photo/videos to be posted in images folder

**Comment by jillianwhiting** [comment]
First tests were varying flow rate:

- videos will be uploaded to drive and analyzed for residence time
- three tests were done at each flow rate of 25,50,75 rpm with size 17 tubing
- faster flow rates were observed to have faster residence times, data will be analyzed to determine the exact relationship

**Comment by jillianwhiting** [comment]
1st string spacing test (26 wraps) flow went only on strings

**Comment by rosiekrasnoff** [comment]
testing for spacing:
we performed the same test of observing the flow while dosing from the pump and reduced the number of strings in the system to see the maximum spacing possible before flow stops following strings and filter would fail.
26 strings - flow stays on strings
20 strings - flow stays on strings
15 strings - flow stays on strings
10 strings at 70 rpm - flow goes along strings but sometimes falls off the string partway down
10 strings at 35 rpm - flow stays on strings
8 strings at 35 rpm - flow stays on strings
6 strings at 35 rpm - flow stays on strings
-6 strings with water on full flow - flow still stays on strings, we notice webbing between two of the strings but all water flows on the strings down to the basin, none of the water doesn't make it onto a string.

**Comment by rosiekrasnoff** [comment]
continued testing:
5 strings at 35 rpm - flow stays on strings
3 strings at 25 rpm - flow stays on strings
1 string in the middle at 20 rpm - flow stays on strings
1 string in the corner at 20 rpm - flow stays on strings
flow was increased and stayed on the string until about 60 rpm, at which point the system failed and the water didn't follow the strings.
