### ISSUE TITLE
Report Draft Revisions: Task List

### ISSUE THREAD

**Issue by BenGassaway** [AguaClara/Trickling-Filter#19]
1. Include heat map of cuvettes with media testing i.e. rocks, marbles
2. String tests
      a. Fabrication iterations
      b. Methods discussion
      c. Variables being tested
3. Design PowerPoint schematic of string structure
4. Future work
      a. Suggestions for team focus in future semesters
           i. Starting points
           ii. Aspirational goals

**Comment by jillianwhiting** [comment]
Portal Time: atom://teletype/portal/d66b65ce-bd28-47d0-8dd5-faa434722220

**Comment by jillianwhiting** [comment]
Future work also added

**Comment by rosiekrasnoff** [comment]
portal time: atom://teletype/portal/05460cbb-cce8-43a4-a02c-182752671b1e
