### ISSUE TITLE
Identify problems with industrial-scale trickling filters 

### ISSUE THREAD

**Issue by jillianwhiting** [AguaClara/Trickling-Filter#2]

**Comment by jillianwhiting** [comment]
Doing general research into trickling filters and how they work, to determine what problems they currently have.

**Comment by rkk57** [comment]
3/1/18 - toured the Cayuga Heights wastewater treatment plant and saw their trickling filters in action. Learning a little about what problems the plant is currently experiencing. Potential opportunity to reach out and get to see data about their effluent, particularly phosphorus levels, which is a focus for the plant.
