### ISSUE TITLE
Buy various types of string for our first experiment

### ISSUE THREAD

**Issue by rosiekrasnoff** [AguaClara/Trickling-Filter#22]

**Comment by antoniopmartinez** [comment]
Link to Polypropylene twine: https://www.mcmaster.com/string
^^Click the one that is called "Grip-Tight Weather-Resistant Twine"

**Comment by MadelineGarell** [comment]
https://www.mcmaster.com/#cable/=4eb62cb6b77646cd930c83d82addf2ecjm6pbnhv 
Multi strand wire rope

**Comment by rosiekrasnoff** [comment]
We want to buy:
1. Grip-Tight Weather-Resistant Twine, dia=0.05 in -- 2078T34 (https://www.mcmaster.com/2078T34) 
2. Clear Nylon Line, dia=0.022in -- 9442T3 (https://www.mcmaster.com/9442T3)
Bend-and-Stay 304 Stainless Steel Wire:
3. dia=0.02 in -- 8860K12 (https://www.mcmaster.com/8860K12)
4. dia=0.051 in -- 8860K16 (https://www.mcmaster.com/8860K16)
5. 18-8 Stainless Steel Wire, dia=1/16 in -- 3461T633 (https://www.mcmaster.com/3461t633)
