### ISSUE TITLE
Develop a robust model for the kinetics of trickling filters 

### ISSUE THREAD

**Issue by BenGassaway** [AguaClara/Trickling-Filter#4]
1.) Compile industry-standard equations that characterize performance and hydraulic properties for a given trickling filter (i.e. different packing materials, residence times, etc.)
2.) Parameterize the system according to design and hydraulic constraints

**Comment by jillianwhiting** [comment]
@AguaClara/uasb Hi friends! The trickling filter team has been doing some research on nitrogen removal kinetics, and it is dependent on BOD concentration. What is the average or range of BOD levels that the UASB would have in its effluent?

**Comment by zacchen15** [comment]
https://www.iwapublishing.com/sites/default/files/ebooks/9781780402116.pdf

Page 82 mentions that removal efficiency is about 65-75%  There are also a few equations to model removal based on a detention time (we're going for 4 hours) on page 93.  

There might also be some good information in Chong 2012: https://ac.els-cdn.com/S0043135412002400/1-s2.0-S0043135412002400-main.pdf?_tid=19065bb5-df4d-40d9-9eb1-432857b4cfc0&acdnat=1520609552_79c5f2a1d14eee7fdadd9ea28e7c1f49 

Hope this help!

**Comment by jillianwhiting** [comment]
@zacchen15 Do you have an expected influent BOD level to go with this removal efficiency?

**Comment by zacchen15** [comment]
@jillianwhiting I don't have any local data from IAWWTF but there is some data about Australian sewage on page 3444 of Chong

**Comment by zacchen15** [comment]
Don't know if you're still working on this but slide 17 has some data on BOD:
https://ocw.tudelft.nl/wp-content/uploads/12._Anaerobic_Sewage_Treatment.pdf
