### ISSUE TITLE
Test differences in preferential flow of prototypes

### ISSUE THREAD

**Issue by jillianwhiting** [AguaClara/Trickling-Filter#8]

**Comment by jillianwhiting** [comment]
Working on writing the procedure and methods for our experiment in atom
fe65842-da35-460f-bed8-1d141bdf419d

**Comment by rosiekrasnoff** [comment]
Fabrication of our model for preferential flow test is complete and we are in the process of finalizing the procedure of tests. We will start our first test when we come back from spring break.

**Comment by rosiekrasnoff** [comment]
Ran bench top model with medium pipe to hold up cuvettes and rocks (height of rocks=?), filled to top. Ran water for ~15 count. 
Results:
![img_6467](https://user-images.githubusercontent.com/35943730/38639368-ea56bc0a-3d9e-11e8-998e-6c4cebaf9ec2.JPG)

A few cells near the middle have water in them, most of the water flowed along the edges of the tube and down the sides, outside the cuvettes or outside of the collection unit entirely.

**Comment by jillianwhiting** [comment]
The team concluded testing in preferential flow with a comparison of marbles and dry and wet rocks. The team's observations is that the wet rocks had the most preferential flow and the marbles had the least. The team will do analysis to come up with a model of flow through the system: Data can be found: https://docs.google.com/spreadsheets/d/1wR-ODf4-iFM-u9-Gaf_OoQsl4m6vnyvG_3m5e8UI_pk/edit?usp=sharing
